language: objective-c
osx_image: xcode9
xcode_project: TLIndexPathTools.xcodeproj
xcode_scheme: TLIndexPathTools
env:
  global: FRAMEWORK_NAME=TLIndexPathTools
before_script:
- brew update
- brew outdated carthage || brew upgrade carthage
- gem install xcpretty
- gem install xcpretty-travis-formatter
before_install:
  - chmod +x build.sh
script:
- ./build.sh
before_deploy:
- carthage build --no-skip-current
- carthage archive $FRAMEWORK_NAME
deploy:
  provider: releases
  api_key:
    secure: jylkFiF1eQUzTHXiMOR28K4CD70Pa8tH0886l8FhADqaJs/bkrHzVphAMYT3bqtv+xPXWAF+ZyMKx1D0kieeq9QO2TVfMMC1l0iDe5BADytZW6u47CzC5IIgGZKhuS76eCJULIrmovZzlyT/b3nx54cyF8jZQgyrw8Jp+VSEW5KnprTWOM4w/A4CWDV2yiea/aK+eLlKCOlD5bFHxnXp1bCuHD/k2wULSVkbPFPwK4g6lF30jfIR1ehY6IcWX5uPyy3sax7oXR+iPH5bW1un6qUNecY5GqhAFrhFtPXOgufqpFUTtW9HpnCeeczxOIlmanCBlwYPS/xxayKuBdfEUld+JQ+WshjudfN/X6ecTfnklrZUnx+AcQ6MymHvRsNSPPhfx4EPL/Rzr3F2qmGJMaeM8SZxbvtUfsvo5HQD1ycAOAdfIYJoYLwJInHJ6GQ9rYJ5XYDZ6myRa8N+XUwIwpvcX+Mw8FljT2+6y5TDAElrgrbJfkX6KNTf8aZ0l89VhAprW1SAlalFD0uxSofx2RVsNbK+MRUEE6146ufwYIl22b1NND25+g1faVIUZueBWzK7D9+tQRdvHdqm2+r9Z22PkGslnDCiyqu2WKfB0cZ5JkScrWH3Ew2vBGUBBbeLvGknglNUtnELKgS2lhMqEUa76BRAfS+cEpLk+WMEy3I=
  file: "$FRAMEWORK_NAME.framework.zip"
  skip_cleanup: true
  on:
    repo: 3a4oT/TLIndexPathTools
    tags: true
